import { page, section, toggles } from './helpers.js';

export default { title: 'Patterns/Product previews' };
export const StyleTile = {
  render: () => page('A look within a look', 'A product preview carries its own tokens. Changing the Sumi theme changes its surroundings while preserving the product’s palette.',
    `<div class="sumi-preview sumi-style-tile sb-narrow" style="--preview-color-bg:#f3eee4;--preview-color-text:#243d36;--preview-color-text-muted:#4e655e;--preview-color-border:#b6c5bb;--preview-card-bg:#fcf9f2;--preview-card-text:#243d36;--preview-card-border:#b6c5bb;--preview-button-primary-bg:#243d36;--preview-button-primary-text:#fcf9f2;--preview-button-secondary-bg:#f3eee4;--preview-button-secondary-text:#243d36;--preview-button-secondary-border:#b6c5bb;--preview-input-bg:#fcf9f2;--preview-input-text:#243d36;--preview-input-border:#b6c5bb;--preview-badge-bg:#dce5dc;--preview-badge-text:#243d36;--preview-radius-control:4px;--preview-font-display:Georgia;--preview-font-body:Outfit">
      <ul class="sumi-swatches">${[['Forest', '#243d36'], ['Paper', '#f3eee4'], ['Sage', '#b6c5bb']].map(([name, color]) => `<li class="sumi-swatch" style="--swatch:${color}"><span class="sr-only">${name}: ${color}</span></li>`).join('')}</ul><p class="sumi-preview-display">A quieter kind of workspace.</p><p class="sumi-preview-body">A sample product direction with its own type, surfaces, and controls.</p><div class="sumi-preview-card"><span class="sumi-preview-badge">In progress</span><span class="sumi-preview-label">Project name</span><span class="sumi-preview-input" aria-hidden="true">Field notes</span><div class="sumi-preview-actions" aria-hidden="true"><span class="sumi-preview-button">Continue</span><span class="sumi-preview-button secondary">Save for later</span></div></div></div>`),
};
export const SketchStates = {
  render: () => page('Before the pixels', 'Sketch frames and explicit screen states help teams discuss the structure of an experience.',
    section('An empty sketch', `<figure class="sumi-sketch-frame"><p class="sumi-sketch-missing">No sketch yet. Choose a screen to begin.</p><figcaption class="sb-note">Workspace overview</figcaption></figure>`) +
    section('Screen states', `<div class="sb-row"><span class="sumi-state is-on">Loading</span><span class="sumi-state is-on">Empty</span><span class="sumi-state is-on">Error</span><span class="sumi-state">Offline — not included</span></div>`) +
    section('A text specimen', `<div class="sumi-specimen-picks" data-single><button class="sumi-choice sumi-specimen-pick" aria-pressed="true"><span class="choice-label">A clear command response</span><span class="sumi-specimen-text">Workspace created.\nInvite your team to start shaping.</span></button><button class="sumi-choice sumi-specimen-pick" aria-pressed="false"><span class="choice-label">A concise response</span><span class="sumi-specimen-text">Ready. Your workspace is open.</span></button></div>`), toggles),
};
